### PR TITLE
Delay six import

### PR DESCRIPTION
**Pull request by wli**
Reference: https://github.com/expo/exponent-server-sdk-python/pull/3

### CODE REVIEW

**Comment by wli** [comment]
@zachd @ide Sorry I introduced the same bug while fixing another instance of it. This should do the trick.

**Comment by marianobrc** [comment]
This issue is making pip install to fail, are you planning to merge the fix soon?
Thnx

**Comment by gorobets-da** [comment]
Unable to use in production due to the fail while installing.

Please, merge this PR.

Thank you.

**Comment by msmaromi** [comment]
@ide could you publish this latest update on pypi?

**Comment by ide** [comment]
We've published 0.1.4 to PyPI: https://pypi.org/project/exponent_server_sdk/#history

The project is also now under community maintenance (the Node SDK is the one we officially support in addition to the HTTP/2 API) so if you would like to become a maintainer of this package please open an issue on [the main Expo repo](https://github.com/expo/expo).

**Pull request merged**
