### PR TITLE
Rename receipts

### PR DESCRIPTION
**Pull request by SibiAkkash**
Renamed variables and classes to conform with the docs

### CODE REVIEW

**Comment by julianpacker** [comment]
pretty standard name change. 

I checked my usage of this code and it won't break any of my code it looks like. But I'm not sure if other people were using these classes directly. Again it'll be on a version upgrade so not the worst but thought I'd mention and see if anyone says anything

**Comment by SibiAkkash** [comment]
Oh nice, yeah let's see if someone is using the classes directly

**Comment by julianpacker** [comment]
Not that this is foolproof or anything, but if no one comments in a couple days I'll just ahead and make the change and a new version release.

**Comment by SibiAkkash** [comment]
Hmm got it 👍

**Pull request merged**
